spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
#      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://1.119.197.163:13306/cloud_plat?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
   application:
      name: spring-boot-jdbc